# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: push
  
jobs:
  reqinstall:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm install gitbook-cli -g
      - run: gitbook init
      - run: gitbook build
      - run: ls
      - run: pwd
      - name: Zip the Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find ./ |grep html|while read line; do sed -i s/'.md'/'.html'/g "${line}"; done
          zip -r release.zip _book
          git config --global user.email ${{ secrets.MAILS }}
          git config --global user.name ${{ secrets.USERNAMES }}
          git add *
          git commit -m "Commit Message"
          git push
      - name: Archive code coverage results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./release.zip
